openapi: 3.0.3
info:
  title: PaperChannel
  description: >-
    ## Abstract
      Questo servizio permette di inviare richieste di invio cartaceo in modo asyncrono e ricevere aggiornamenti
      sul loro stato di avanzamento. Nello specifico: <br/>
          - Raccomandata Internazionale, <br/>
          - Raccomandata Semplice, <br/>
          - Raccomandata con ricevuta di ritorno, <br/>
          - Raccomandata a norma di legge 890/1982. <br/>
  license:
    name: PN software license
    url: 'https://www.pn.pagopa.it/LICENSE'
  version: v1.0
servers:
  - url: >-
      https://api.paperchannel.pagopa.local
    description: Server url
tags:
  - name: PaperMessages
    description: Operazioni per inviare e monitorare messaggi di corrispondenza cartacea
paths:

    #############################################################################################
    ###                                  PAPER MAIL MESSAGES                                  ###
    #############################################################################################
  /paper-channel/v1/paper-deliveries-send/{requestIdx}/engageid/{engageId}:
    parameters:
      - $ref: '#/components/parameters/requestIdx'
      - $ref: '#/components/parameters/engageId'
    post:
      operationId: sendPaperEngageSendRequest
      tags:
        - PaperMessages
      summary: Invio di corrispondenza cartacea
      description: >-
        Questa operazione sottomette ad paper-channel una richiesta di invio di corrispondenza
        cartacea precedentemente calcolata. <br/>
        Paper channel deve validare la richiesta in base all'engageId passato e, se tale validazione ha
        successo, registrare la richiesta in maniera sincrona. Se vengono inviate molteplici
        richieste con lo stesso requestId e lo stesso engageId solo una deve avere successo (status code HTTP 204, le
        altre devono ricevere lo status code 409).
    responses:
      '204':
        $ref: '#/components/responses/EngageSendResponse'
      '400':
        $ref: '#/components/responses/EngageSendResponseBad'
      '404':
        $ref: '#/components/responses/EngageSendResponseNotFound'
      '409':
        $ref: '#/components/responses/EngageSendResponseDuplicated'
    callbacks:
      deliveryStatusPushUpdates:
        'indirizzo_webhook_oppure_coda_sqs_legato_al_valore_header_xPagopaExtchCxId':
          post:
            summary: Eventi avanzamento spediti ad SQS
            requestBody:
              content:
                application/json:
                  schema:
                    type: array
                    minItems: 1
                    maxItems: 1000
                    items:
                      $ref: '#/components/schemas/SingleStatusUpdate'
              required: true
            responses:
              default:
                description: Error processing the update, the update must be re-sended
              '200':
                description: Update correctly received
              '400':
                description: Malformed update status

  /paper-channel/v1/paper-deliveries-prepare/{requestIdx}:
    parameters:
      - $ref: '#/components/parameters/requestIdx'
    post:
      operationId: sendPaperEngageRequest
      tags:
        - PaperMessages
      summary: Invio di corrispondenza cartacea
      description: >- 
        Questa operazione sottomette ad paper-channel una richiesta di invio di corrispondenza
        cartacea. <br/>
        Paper channel deve validare la sintatticamente la richiesta e, se tale validazione ha
        successo, registrare la richiesta in maniera sincrona. Se vengono inviate molteplici 
        richieste con lo stesso requestId solo una deve avere successo (status code HTTP 204, le 
        altre devono ricevere lo status code 409).
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaperEngageRequest'
        required: true
      responses:
        '204':
          $ref: '#/components/responses/putDeliveryOk'
        '400':
          $ref: '#/components/responses/putDeliveryBad'
        '409':
            $ref: '#/components/responses/putDeliveryDuplicated'
      callbacks:
        deliveryStatusPushUpdates:
          'indirizzo_webhook_oppure_coda_sqs_legato_al_valore_header_xPagopaExtchCxId':
            post:
              summary: Eventi avanzamento spediti ad SQS
              requestBody:
                content:
                  application/json:
                    schema:
                      type: array
                      minItems: 1
                      maxItems: 1000
                      items:
                        $ref: '#/components/schemas/SingleStatusUpdate'
                required: true
              responses:
                default:
                  description: Error processing the update, the update must be re-sended
                '200':
                  description: Update correctly received
                '400':
                  description: Malformed update status
    
    get:
      operationId: getPaperEngageProgresses
      tags:
        - PaperMessages
      summary: Pull avanzamenti messaggi cartacei
      description: >- 
        Questa richiesta permette di ottenere l'elenco degli eventi salienti 
        riguardanti un processo di postalizzazione. <br/>
        Oltre all'elenco degli eventi si ottengono informazioni sulle cause di tali eventi 
        e URL per effettuare il download delle scansioni digitali dei documenti prodotti 
        durante il processo di postalizzazione. <br>
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaperProgressStatusEvent'
        '404':
          $ref: '#/components/responses/getDeliveryStatusHistoryNotFound'

components:
  
    #############################################################################################
    ###             PARAMETRI E RISPOSTE IN COMUNE PER TUTTI I TIPI DI MESSAGGIO              ###
    #############################################################################################
  parameters:

    requestIdx:
      name: requestIdx
      in: path
      required: true
      schema:
        type: string
#        pattern: '[0-9A-Za-z_-]'
        minLength: 5
        maxLength: 100
  
  responses:
    
    EngagePrepareResponse:
      description: OK/KO
      result:
        description: // TODO avvisa solo del presa in carico
        enum:
          - OK
          - KO

    EngageSendResponse:
      cost:
        description: ammontare in eurocent del costo per l'invio della notifica in forma cartacea
        type: number
      receiverAddress:
        description: indirizzo al quale verrà spedita la notifica
        type: object
        schema:
          $ref: '#/components/schemas/Address'

    
    EngageSendResponseBad:
      description: Errore di validazione sintattica della richiesta
      content:
        application/json:
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/Problem'

    EngageSendResponseDuplicated:
      description: >-
        Indica che la richiesta è già stata effettuata e non può essere sovrascritta.
      content:
        application/json:
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/Problem'

    EngageSendResponseNotFound:
      description: >-
        Indica che la richiesta con la coppia requestIdx-engageId non è stata trovata
      content:
        application/json:
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/Problem'
    
    putDeliveryDuplicated:
      description: >-
        Indica che la richiesta è già stata effettuata e non può essere sovrascritta.
      content:
        application/json:
          schema:
            $ref: 'schemas-pn-errors-v1.yaml#/components/schemas/Problem'
    
    getDeliveryStatusHistoryNotFound:
      description: requestIdNotFound
      content:
        application/json:
          schema:
            $ref: 'schemas-pn-errors-v1.yaml#/components/schemas/Problem'
  
  schemas:
    
    ### - DTO PER RICEZIONE ASINCRONA AVANZAMENTI MESSAGGI
    ######################################################

    PaperChannelUpdate:
      type: object
      properties:
        preEngageEvent:
          $ref: '#/components/schemas/PaperProgressStatusEvent'
        analogEvent:
          $ref: '#/components/schemas/PaperProgressStatusEvent'
    

    ### - RIFERIMENTI AD ALTRI FILE
    ######################################################
    PaperEngageRequest:
      $ref: 'schemas-paper-v1.yaml#/components/schemas/PaperEngageRequest'
    PaperProgressStatusEvent:
      $ref: 'schemas-paper-v1.yaml#/components/schemas/PaperProgressStatusEvent'
      
    

#  securitySchemes:        # ONLY EXTERNAL
#    ApiKeyAuth:           # ONLY EXTERNAL
#      type: apiKey        # ONLY EXTERNAL
#      in: header          # ONLY EXTERNAL
#      name: x-api-key     # ONLY EXTERNAL

#security:                 # ONLY EXTERNAL
#  - ApiKeyAuth: [] # use the same name as under securitySchemes    # ONLY EXTERNAL
              
