openapi: 3.0.3
info:
  termsOfService: https://termofservice.it
  x-api-id: api-paper-channel-private
  x-summary: OpenAPI servizio PaperChannel ad uso solo interno
  title: PaperChannel
  description: |-
    ## Abstract
      Questo servizio permette di inviare richieste di invio cartaceo in modo asyncrono e ricevere aggiornamenti
      sul loro stato di avanzamento. Nello specifico: <br/>
          - Raccomandata Internazionale, <br/>
          - Raccomandata Semplice, <br/>
          - Raccomandata con ricevuta di ritorno, <br/>
          - Raccomandata a norma di legge 890/1982. <br/>
  contact:
    email: pn@pagopa.it
  license:
    name: PN software license
    url: https://www.pn.pagopa.it/LICENSE
  version: '1.0.0'
servers:
  - url: https://api.paperchannel.pagopa.local
    description: Server url
tags:
  - name: PaperMessages
    description: Operazioni per inviare e monitorare messaggi di corrispondenza cartacea
  - name: HealthCheck
    description: Metodo heartbeat
paths:
  '/status':
    get:
      summary: healthCheck path
      description: healtCheck path per verificare lo stato del microservizio
      tags:
        - HealthCheck
      operationId: status
      responses:
        '200':
          description: Ok
        '500':
          description: Internal Server Error
  /paper-channel-private/v1/b2b/paper-deliveries-send/{requestId}:
    get:
      tags:
        - PaperMessages
      summary: Pull stato per richieste già inviate
      description: "Questa richiesta permette di ottenere l'esito per la richiesta\
        \ di send precedentemente inviata. <br/> Se presente, torna l'evento relativo\
        \ allo stato corrente di send."
      operationId: retrievePaperSendRequest
      parameters:
        - name: requestId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 100
            minLength: 5
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendEvent'
        "404":
          description: Indica che la richiesta con requestId non è stata trovata
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
    post:
      tags:
        - PaperMessages
      summary: Invio di corrispondenza cartacea
      description: "Questa operazione sottomette ad paper-channel una richiesta di\
        \ invio di corrispondenza cartacea precedentemente preparata. <br/> Paper\
        \ channel deve validare la richiesta in base al requestId passato e, se tale\
        \ validazione ha successo, registrare la richiesta in maniera sincrona invocando\
        \ external-channel. Se l'invocazione a external-channel ha successo, a questo\
        \ punto può tornare nella response il costo in eurocent e l'indirizzo effettivo\
        \ a cui verrà inviata la comunicazione cartacea. Se vengono inviate molteplici\
        \ richieste con lo stesso requestId il servizio deve ritornare lo stesso risultato\
        \ precedentemente calcolato."
      operationId: sendPaperSendRequest
      parameters:
        - name: requestId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 100
            minLength: 5
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendRequest'
        required: true
      responses:
        "200":
          description: Risposta positiva di invio cartaceo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
        "400":
          description: Errore di validazione sintattica della richiesta
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        "404":
          description: Indica che la richiesta con tenderId non è stata trovata oppure che il cap/zona inviata non esistono oppure sono stati dismessi
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        "409":
          description: Indica che la richiesta è già stata effettuata e non può essere
            sovrascritta.
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        "422":
          description: Indica che la richiesta non può essere evasa per un cambio di costo tra prepare e send, e che necessario rieseguire la prepare.
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
      callbacks:
        deliveryStatusPushUpdates:
          indirizzo_webhook_oppure_coda_sqs_legato_al_valore_header_xPagopaExtchCxId:
            post:
              summary: Eventi avanzamento spediti ad SQS
              requestBody:
                content:
                  application/json:
                    schema:
                      maxItems: 1000
                      minItems: 1
                      type: array
                      items:
                        $ref: '#/components/schemas/PaperChannelUpdate'
                required: true
              responses:
                default:
                  description: "Error processing the update, the update must be re-sended"
                "200":
                  description: Update correctly received
                "400":
                  description: Malformed update status
  /paper-channel-private/v1/b2b/paper-deliveries-prepare/{requestId}:
    get:
      tags:
        - PaperMessages
      summary: Pull esito ed eventuale indirizzo da usare per richieste già inviate
      description: "Questa richiesta permette di ottenere l'esito corrente per la\
        \ richiesta di prepare precedentemente inviata. <br/> Se presente, torna l'evento\
        \ relativo allo stato corrente di prepare con eventuale indirizzo da usare."
      operationId: retrievePaperPrepareRequest
      parameters:
        - name: requestId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 100
            minLength: 5
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrepareEvent'
        "404":
          description: Errore di lettura richiesta non trovata
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
    post:
      tags:
        - PaperMessages
      summary: Invio di corrispondenza cartacea - richiesta di validazione e praparazione
        all'invio
      description: "Questa operazione sottomette ad paper-channel una richiesta preparazione\
        \ di invio di corrispondenza cartacea. <br/> Paper channel deve validare sintatticamente\
        \ la richiesta in maniera sincrona in base ai parametri passati, ritornare\
        \ l'OK di presa in carico (204) o la conferma dell'indirizzo da usare (200)\
        \ se già elaborata in precedenza. Nel caso di presa in carico (204), in asincrono\
        \ poi dovrà eventualmente recuperare le informazioni da pn-national-registries\
        \ e ritornare l'indirizzo corretto da usare. Se vengono inviate molteplici\
        \ richieste con lo stesso requestId ma informazioni funzionalmente differenti\
        \ (es indirizzo diverso) va previsto il codice 409. Se con lo stesso requestId\
        \ ma stessi parametri passati, si può tornare il codice 200 se la richiesta\
        \ è già stata elaborata (o si conosce già l'esito), o il 204 se è ancora in\
        \ fase di elaborazione. I dati relativi alla richiesta vanno mantenuti in\
        \ forma anonima tramite opportuno hash. \
        \ E' possibile riceve al più un url relativo a f24, relativo ad un set di\
        \ documenti f24 da generare. La risposta alla prepare, conterrà la lista\
        \ delle fileKey di safestorage generate da pn-f24"
      operationId: sendPaperPrepareRequest
      parameters:
        - name: requestId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 100
            minLength: 5
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrepareRequest'
        required: true
      responses:
        "200":
          description: Risposta positiva ad una ulteriore chiamata di invio cartaceo 
            con stesso requestId e body della prima. Questo è il caso in cui il client effettua
            una nuova richiesta del tutto identica alla prima. 
            In questo scenario il componente risponderà con l'ultimo evento di aggiornamento 
            sullo stato di lavaorazione della richiesta.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaperChannelUpdate'
        "204":
          description: Risposta positiva di un invio cartaceo con un nuovo requestID, 
            lo status code indica che servizio ha preso in carico la richiesta
        "400":
          description: Errore di validazione sintattica della richiesta
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        "409":
          description: Indica che la richiesta è già stata effettuata e non può essere
            sovrascritta.
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
      callbacks:
        deliveryStatusPushUpdates:
          indirizzo_webhook_oppure_coda_sqs_legato_al_valore_header_xPagopaExtchCxId:
            post:
              summary: Eventi avanzamento spediti ad SQS
              requestBody:
                content:
                  application/json:
                    schema:
                      maxItems: 1000
                      minItems: 1
                      type: array
                      items:
                        $ref: '#/components/schemas/PaperChannelUpdate'
                required: true
              responses:
                default:
                  description: "Error processing the update, the update must be re-sended"
                "200":
                  description: Update correctly received
                "400":
                  description: Malformed update status

  /paper-channel-private/v2/tenders/{tenderId}/cost/calculate:
    post:
      tags:
        - PaperCalculator
      summary: Calcolo del costo di una spedizione
      description: "Questa operazione sottomette ad paper-channel una richiesta di\
        \ simulazione di calcolo del costo analogico di una spedizione, in base\
        \ agli input forniti. Paper Channel deve validare i parametri di input e\
        \ calcolare il costo della spedizione che deve essere restituito al chiamante."
      operationId: calculateCost
      parameters:
        - name: tenderId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 100
            minLength: 5
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShipmentCalculateRequest'
        required: true
      responses:
        "200":
          description: Risposta positiva di calcolo del costo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipmentCalculateResponse'
        "400":
          description: Errore di validazione sintattica della richiesta
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        "404":
          description: Indica che la richiesta con tenderId non è stata trovata
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'

  /paper-channel-private/v1/b2b/pc-retry/{requestId}:
    get:
      tags:
        - PcRetry
      summary: Verifica se ci sono altri retry
      description: ""
      operationId: getPcRetry
      parameters:
        - $ref: '#/components/parameters/pathRequestId'
        - name: checkApplyRasterization
          in: query
          required: true
          schema:
            type: boolean
            default: false
          description: true in caso di richiesta per evento CON996, false per tutti gli altri eventi di retry
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PcRetryResponse'
        "404":
          description: Indica che la richiesta con requestId non è stata trovata
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'

components:

  #############################################################################################
  ###             PARAMETRI E RISPOSTE IN COMUNE PER TUTTI I TIPI DI MESSAGGIO              ###
  #############################################################################################
  parameters:

    pathRequestId:
      name: requestId
      in: path
      required: true
      schema:
        type: string
        minLength: 5
        maxLength: 100
    tenderId:
      name: tenderId
      in: path
      required: true
      schema:
        type: string
        minLength: 5
        maxLength: 100

  responses:

    SendResponse:
      description: Risposta positiva di invio cartaceo
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendResponse'

    SendResponseBad:
      description: Errore di validazione sintattica della richiesta
      content:
        application/json:
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/Problem'

    SendResponseDuplicated:
      description: "Indica che la richiesta è già stata effettuata e non può essere sovrascritta."
      content:
        application/json:
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/Problem'


    SendResponseNotFound:
      description: "Indica che la richiesta con requestId non è stata trovata"
      content:
        application/json:
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/Problem'


    PrepareResponse:
      description: Risposta positiva di invio cartaceo
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendEvent'

    PrepareResponseBad:
      description: Errore di validazione sintattica della richiesta
      content:
        application/json:
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/Problem'

    PrepareResponseNotFound:
      description: Errore di lettura richiesta non trovata
      content:
        application/json:
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/Problem'

    PrepareResponseDuplicated:
      description: "Indica che la richiesta è già stata effettuata e non può essere sovrascritta."
      content:
        application/json:
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/Problem'

    ShipmentCalculateResponse:
      description: Risposta positiva di calcolo del costo
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ShipmentCalculateResponse'

  schemas:

    PcRetryResponse:
      type: object
      properties:
        requestId:
          type: string
          description: Nuovo identificativo con PcRetry se presente
        parentRequestId:
          type: string
          description: requestId padre da cui è stato generato il nuovo requestId
        deliveryDriverId:
          type: string
          description: Id recapitista
        pcRetry:
          type: string
        retryFound:
          type: boolean
          description: Indica se sono stati trovati retry per la richiesta

    ######################################################
    ### - DTO PER RICEZIONE ASINCRONA AVANZAMENTI RICHIESTE
    ######################################################

    PaperChannelUpdate:
      description: oggetto usato per ricevere un evento nella coda. >-
        Prevede di valorizzare solo uno dei tipi di eventi possibili
        A questi si aggiunge il clientId che ha generato la richiesta, quando disponibile
      type: object
      properties:
        prepareEvent:
          $ref: '#/components/schemas/PrepareEvent'
        sendEvent:
          $ref: '#/components/schemas/SendEvent'
        clientId:
          type: string


    ### - RIFERIMENTI AD ALTRI FILE
    ######################################################
    SendRequest:
      $ref: 'schemas-paper-v1.yaml#/components/schemas/SendRequest'
    SendResponse:
      $ref: 'schemas-paper-v1.yaml#/components/schemas/SendResponse'
    PrepareEvent:
      $ref: 'schemas-paper-v1.yaml#/components/schemas/PrepareEvent'
    SendEvent:
      $ref: 'schemas-paper-v1.yaml#/components/schemas/SendEvent'
    PrepareRequest:
      $ref: 'schemas-paper-v1.yaml#/components/schemas/PrepareRequest'

    ShipmentCalculateRequest:
      type: object
      required:
        - product
        - geokey
        - numSides
        - isReversePrinter
      properties:
        product:
          type: string
          description: Prodotto Postale
          example: AR
          enum:
            - AR
            - RS
            - '890'
            - RIR
            - RIS
        geokey:
          type: string
          description: CAP o Stato Estero
          example: 00100
        numSides:
          type: integer
          description: Numero di facciate che compongono il documento
          format: int32
          example: 5
        isReversePrinter:
          type: boolean
          description: Indica se la stampa è fronte-retro
        pageWeight:
          type: integer
          description: Indica il peso del foglio
          format: int32
          example: 15
    ShipmentCalculateResponse:
      type: object
      properties:
        cost:
          type: integer
          description: Costo calcolato alla spedizione in eurocents
          format: int32
          example: 350

#  securitySchemes:        # ONLY EXTERNAL
#    ApiKeyAuth:           # ONLY EXTERNAL
#      type: apiKey        # ONLY EXTERNAL
#      in: header          # ONLY EXTERNAL
#      name: x-api-key     # ONLY EXTERNAL

#security:                 # ONLY EXTERNAL
#  - ApiKeyAuth: [] # use the same name as under securitySchemes    # ONLY EXTERNAL