openapi: 3.0.3
info:
  title: API Paper Channel
  description: |
    # Interface definition for Paper Channel
  version: 1.0.0
  contact:
    name: API Support
    url: http://www.pagopa.com/support
    email: support@pagopa.com
  termsOfService: termsOfService
  x-api-id: ppr-chnnl
  x-summary: smmry

servers:
  - url: 'https://.*'
    description: Server url

security:
  - ApiKeyAuth: []

tags:
  - name: HealthCheck
    description: metodo di health
  - name: DeliveryDriver
    description: operazioni legate ai recapitisti

paths:
  /status:
    get:
      tags:
        - HealthCheck
      operationId: takeHealth
      summary: Info health.
      description: Ritorna lo status di salute dell'API.
      responses:
        '200':
          description: JSON contenente lo stato.

  /paper-channel/backoffice/v1/deliveries-drivers:
    get:
      tags:
        - DeliveryDriver
      operationId: takeDeliveryDriver
      summary: Elenco recapitisti.
      description: API che consente il recupero di tutti i vincitori della gara
      parameters:
        - name: page
          in: query
          description: Risultati di pagina che si vuole ottenere (0..N)
          required: false
          schema:
            type: integer
            default: 0
            format: int32
            maximum: 999999999
            minimum: 0
        - name: size
          in: query
          description: Numero di elementi per pagina.
          required: false
          schema:
            type: integer
            default: 5
            format: int32
            maximum: 999999999
            minimum: 1
        - name: status
          in: query
          description: Rappresenta lo stato di attività del vincitore
          required: false
          schema:
            type: boolean
            default: true
        - name: startDate
          in: query
          description: Rappresenta la data di inizio del contratto
          required: false
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          description: Rappresenta la data di termine del contratto
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageableDeliveryDriverResponseDto'
        '400':
          $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/NotAllowed'
        '500':
          $ref: '#/components/responses/InternalError'


  /paper-channel/backoffice/v1/delivery-driver/{deliveryDriverId}/prices:
    get:
      tags:
        - DeliveryDriver
      operationId: takePrices
      summary: Listino prezzi.
      description: API che consente il recupero dei prezzi di un vincitore
      parameters:
        - $ref: '#/components/parameters/pathDeliveryDriverId'
        - $ref: '#/components/parameters/queryType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllPricesContractorResponseDto'
        '400':
          $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/NotAllowed'
        '500':
          $ref: '#/components/responses/InternalError'

  /paper-channel/backoffice/v1/delivery-tender/contract:
    post:
      tags:
        - DeliveryDriver
      operationId: addContract
      summary: Inserimento contratto.
      description: API che consente di aggiungere un nuovo contratto
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractInsertRequestDto'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/NotAllowed'
        '500':
          $ref: '#/components/responses/InternalError'


  /paper-channel/backoffice/v1/contract/{deliveryDriverId}/{contractId}:
    put:
      tags:
        - DeliveryDriver
      operationId: updateContract
      summary: Aggiornamento contratto.
      description: API che consente di aggiornare un nuovo contratto
      parameters:
        - $ref: '#/components/parameters/pathDeliveryDriverId'
        - $ref: '#/components/parameters/pathContractId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractInsertRequestDto'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/NotAllowed'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    AllPricesContractorResponseDto:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/BaseResponse'
        data:
          $ref: '#/components/schemas/AllPricesDeliveryDriverDto'
      additionalProperties: false

    AllPricesDeliveryDriverDto:
      type: object
      properties:
        nationals:
          type: array
          items:
            $ref: '#/components/schemas/NationalContractDto'
          maxItems: 999999999
          minItems: 1
        internationals:
          type: array
          items:
            $ref: '#/components/schemas/InternationalContractDto'
          maxItems: 999999999
          minItems: 1
      additionalProperties: false

    ContractInsertRequestDto:
      type: object
      allOf:
        - $ref: '#/components/schemas/DeliveryDriverDto'
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/ContractDto'
          maxItems: 999999999
          minItems: 1
      additionalProperties: false

    ContractDto:
      type: object
      oneOf:
        - $ref: '#/components/schemas/NationalContractDto'
        - $ref: '#/components/schemas/InternationalContractDto'
      discriminator:
        propertyName: registeredLetter
      properties:
        price:
          type: number
          format: float
          maximum: 999999
          minimum: 1
        priceAdditional:
          type: number
          format: float
          maximum: 999999
          minimum: 1
      additionalProperties: false

    NationalContractDto:
      type: object
      properties:
        registeredLetter:
          $ref: '#/components/schemas/TypeRegisteredLetterEnum'
        cap:
          type: string
          pattern: '^[0-9]{5}$'
          maxLength: 5
          minLength: 5
        price:
          type: number
          format: decimal64
          maximum: 1
          minimum: 1
        priceAdditional:
          type: number
          format: decimal64
          maximum: 1
          minimum: 1
      additionalProperties: false

    InternationalContractDto:
      type: object
      properties:
        registeredLetter:
          $ref: '#/components/schemas/TypeRegisteredLetterInterEnum'
        zone:
          $ref: '#/components/schemas/InternationalZoneEnum'
        price:
          type: number
          format: decimal64
          maximum: 1
          minimum: 1
        priceAdditional:
          type: number
          format: decimal64
          maximum: 1
          minimum: 1
      additionalProperties: false

    TypeRegisteredLetterEnum:
      type: string
      enum:
        - AR
        - '890'
        - SEMPLICE

    TypeRegisteredLetterInterEnum:
      type: string
      enum:
        - AR_INTER
        - SEMPLICE_INTER

    InternationalZoneEnum:
      type: string
      enum:
        - ZONE_1
        - ZONE_2
        - ZONE_3

    PageableDeliveryDriverResponseDto:
      type: object
      allOf:
        - $ref: '#/components/schemas/Page'
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryDriverDto'
          maxItems: 999999999
          minItems: 1
      additionalProperties: false

    DeliveryDriverDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          maximum: 64
          minimum: 1
        denomination:
          type: string
          example: 'Denominazione'
          format: '/^([a-zA-Z ]*)$/'
          maxLength: 128
        businessName:
          type: string
          example: 'Ragione sociale'
          format: '/^([a-zA-Z ]*)$/'
          maxLength: 128
        registeredOffice:
          type: string
          example: 'Sede legale'
          format: '/^([a-zA-Z ]*)$/'
          maxLength: 128
        pec:
          type: string
          example: 'email.example@pec.com'
          format: '/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/'
          maxLength: 64
        codeFiscal:
          type: string
          example: 'ABCDEF22G12H345K'
          format: '/^[A-Za-z]{6}[0-9]{2}[A-Za-z]{1}[0-9]{2}[A-Za-z]{1}[0-9]{3}[A-Za-z]{1}$/'
          maxLength: 16
        taxId:
          type: string
          example: '12345678900'
          format: '/^[0-9]{11}$/'
          maxLength: 32
        phoneNumber:
          type: string
          example: '+39012345678'
          format: '/^(([\+]?)[0-9]{1,}([\/]?)[0-9]*([\-]?)[0-9]*)$/'
          maxLength: 32
        uniqueCode:
          type: string
          example: 'A12C34D56789E0'
          format: '/[^A-Za-z0-9]+/'
          maxLength: 32
        fsu:
          type: boolean
      additionalProperties: false

    Pageable:
      type: object
      properties:
        offset:
          type: integer
          format: int64
          maximum: 999999999
          minimum: 1
        pageNumber:
          type: integer
          format: int32
          maximum: 999999999
          minimum: 1
        pageSize:
          type: integer
          format: int32
          maximum: 999999999
          minimum: 1
        paged:
          type: boolean
        sort:
          $ref: '#/components/schemas/Sort'
        unpaged:
          type: boolean
      additionalProperties: false

    Sort:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
      additionalProperties: false

    Page:
      type: object
      properties:
        empty:
          type: boolean
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
          format: int32
          maximum: 999999999
          minimum: 1
        numberOfElements:
          type: integer
          format: int32
          maximum: 999999999
          minimum: 1
        pageable:
          $ref: '#/components/schemas/Pageable'
        size:
          type: integer
          format: int32
          maximum: 1024
          minimum: 1
        sort:
          $ref: '#/components/schemas/Sort'
        totalElements:
          type: integer
          format: int64
          maximum: 1
          minimum: 1
        totalPages:
          type: integer
          format: int64
          maximum: 999999999
          minimum: 1
      additionalProperties: false

    BaseResponse:
      type: object
      properties:
        result:
          type: boolean
        code:
          description: |
            Return code.
            * 0 -> OK 
            * 1 -> Other error
            * 2 -> Other error
            * 99 -> KO
          type: number
          format: decimal32
          enum: [0,1,2,3,99]
          maximum: 999999999
          minimum: 1
      additionalProperties: false

  responses:
    Forbidden:
      description: Forbidden
    NotFound:
      description: Not found
    Invalid:
      description: Bad Request
    NotAllowed:
      description: Method not allowed
    InternalError:
      description: Internal Server Error
    Unauthorized:
      description: Unauthorized

  parameters:
    pathDeliveryDriverId:
      name: deliveryDriverId
      in: path
      required: true
      schema:
        type: integer
        format: int64
        maximum: 1
        minimum: 1
    pathContractId:
      name: contractId
      in: path
      required: true
      schema:
        type: integer
        format: int64
        maximum: 1
        minimum: 1
    queryType:
      name: type
      in: query
      schema:
        type: string
        enum:
          - NATIONAL
          - INTERNATIONAL
        maximum: 1
        minimum: 1
  
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key      