logging.config=config/logback-local.xml


pn.env.runtime=PROD
  
  # Queue inbound event configuration
spring.cloud.stream.function.routing.enabled=true
spring.cloud.stream.bindings.functionRouter-in-0.destination=local-delivery-push-inputs.fifo,local-ext-channels-outputs,local-delivery-push-actions,local-delivery-push-actions-done
spring.cloud.stream.sqs.bindings.functionRouter-in-0.consumer.snsFanout=false

cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
cloud.aws.region.static= us-east-1

aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.ready-delivery-queue=local-delivery-push-safestorage-inputs
aws.dynamodb-request-delivery-table=RequestDeliveryDynamoTable
