AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

   #ApiDnsName:
   #  Type: String
   #  Description: 'The DNS name used for B2B rest API.'

  WebApiDnsName:
    Type: String
    Description: 'The DNS name used for WEB rest API.'
  
  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'
  
  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  SandboxSafeStorageBaseUrl:
    Type: String
    Description: 'Url to the SafeStorage microservice'

  AttemptSafeStorage:
    Type: Number
    Description: 'Number of attempts for retrieve file on safe storage'

  AttemptQueueExternalChannel:
    Type: Number
    Description: 'Number of attempts for called external channel'

  AttemptQueueNationalRegistries:
    Type: Number
    Description: 'Number of attempts for called national registries'

  AttemptQueueSafeStorage:
    Type: Number
    Description: 'Number of attempts for called prepare async for retry retrieve file'

  SafeStorageCxId:
    Type: String
    Description: 'SafeStorage cx-id'

  XPagopaExtchCxId:
    Type: String
    Description: 'SafeStorage cx-id'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  PCKmsEncDecDynamoDataKeyARN:
    Type: String
    Description: 'Name of KMS Key for Dynamo encode/decode data'

  PaperDeliveryDriversBucketName:
    Type: String
    Description: 'Name of S3 bucket'

  RequestDeliveryDynamoTableName:
    Type: String
    Description: 'Name of dynamodb table containing request'

  RequestDeliveryDynamoTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing request'

  DeliveryFileDynamoTableName:
    Type: String
    Description: 'Name of dynamodb table containing file request'

  DeliveryFileDynamoTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing file request'

  AddressDynamoTableName:
    Type: String
    Description: 'Name of dynamodb table containing address of request delivery'

  AddressDynamoTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing address of request delivery'

  TenderDynamoTableName:
    Type: String
    Description: 'Name of dynamodb table containing tenders'

  TenderDynamoTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing tenders'

  DeliveryDriverDynamoTableName:
    Type: String
    Description: 'Name of dynamodb table containing delivery drivers'

  DeliveryDriverDynamoTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing delivery drivers'

  CostDynamoTableName:
    Type: String
    Description: 'Name of dynamodb table containing cost'

  CostDynamoTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing cost'

  ZoneDynamoTableName:
    Type: String
    Description: 'Name of dynamodb table containing zone'

  ZoneDynamoTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing zone'

  CapDynamoTableName:
    Type: String
    Description: 'Name of dynamodb table containing cap'

  CapDynamoTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing cap'

  ExternalChannelsOutputsQueueName:
    Type: String
    Description: 'Push delivery-push messages to this Queue'

  ExternalChannelsOutputsQueueARN:
    Type: String
    Description: 'Push delivery-push messages to this Queue'

  NationalRegistryGatewayOutputsQueueName:
    Type: String
    Description: 'Pull nationa-registry messages to this Queue'

  NationalRegistryGatewayOutputsQueueARN:
    Type: String
    Description: 'Pull nationa-registry messages to this Queue'

  ExternalChannels2PaperChannelQueueName:
    Type: String
    Description: 'Pull external-channel messages from this Queue'

  ExternalChannels2PaperChannelQueueARN:
    Type: String
    Description: 'Pull external-channel messages from this Queue'

  ScheduledRequestsQueueName:
    Type: String
    Description: 'Send and pull requests in this queue'

  ScheduledRequestsQueueARN:
    Type: String
    Description: 'Send and pull requests in this queue'

  # OpenApi Bucket params
  MicroserviceBucketName:
    Type: String
    Default: ''
    Description: 'Name of the bucket where the microservice files are copied during deploy'

  MicroserviceBucketBaseKey:
    Type: String
    Default: ''
    Description: 'Base key of the microservice in the s3 bucket'

Resources:
  # PN-Paper-Channel microservice
  PaperChannelMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-paper-channel'
        CpuValue: 1024
        MemoryAmount: 2GB
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'CORS_ALLOWED_DOMAINS=${CorsAllowedDomains}, http://localhost:3000'
        ContainerEnvEntry3: !Sub 'PN_PAPERCHANNEL_CLIENTSAFESTORAGEBASEPATH=${SandboxSafeStorageBaseUrl}'
        ContainerEnvEntry4: !Sub 'PN_PAPERCHANNEL_CLIENTNATIONALREGISTRIESBASEPATH=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry5: !Sub 'PN_PAPERCHANNEL_CLIENTEXTERNALCHANNELBASEPATH=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry6: !Sub 'PN_PAPERCHANNEL_SAFESTORAGECXID=${SafeStorageCxId}'
        ContainerEnvEntry7: !Sub 'PN_PAPERCHANNEL_XPAGOPAEXTCHCXID=${XPagopaExtchCxId}'
        ContainerEnvEntry8: !Sub 'AWS_DYNAMODBREQUESTDELIVERYTABLE=${RequestDeliveryDynamoTableName}'
        ContainerEnvEntry9: !Sub 'AWS_DYNAMODBADDRESSTABLE=${AddressDynamoTableName}'
        ContainerEnvEntry10: !Sub 'AWS_DYNAMODBTENDERTABLE=${TenderDynamoTableName}'
        ContainerEnvEntry11: !Sub 'AWS_DYNAMODBDELIVERYDRIVERTABLE=${DeliveryDriverDynamoTableName}'
        ContainerEnvEntry12: !Sub 'AWS_DYNAMODBCOSTTABLE=${CostDynamoTableName}'
        ContainerEnvEntry13: !Sub 'AWS_DYNAMODBZONETABLE=${ZoneDynamoTableName}'
        ContainerEnvEntry14: !Sub 'AWS_DYNAMODBCAPTABLE=${CapDynamoTableName}'
        ContainerEnvEntry15: !Sub 'AWS_DYNAMODBDELIVERYFILETABLE=${DeliveryFileDynamoTableName}'
        ContainerEnvEntry16: !Sub 'AWS_KMS_KEYID=${PCKmsEncDecDynamoDataKeyARN}'
        ContainerEnvEntry17: !Sub 'AWS_KMS_REGION=${AWS::Region}'
        ContainerEnvEntry18: !Sub 'PN_PAPERCHANNEL_QUEUEDELIVERYPUSH=${ExternalChannelsOutputsQueueName}'
        ContainerEnvEntry19: !Sub 'PN_PAPERCHANNEL_QUEUEEXTERNALCHANNEL=${ExternalChannels2PaperChannelQueueName}'
        ContainerEnvEntry20: !Sub 'PN_PAPERCHANNEL_QUEUENATIONALREGISTRIES=${NationalRegistryGatewayOutputsQueueName}'
        ContainerEnvEntry21: !Sub 'PN_PAPERCHANNEL_QUEUEINTERNAL=${ScheduledRequestsQueueName}'
        ContainerEnvEntry22: !Sub 'PN_PAPERCHANNEL_ATTEMPTSAFESTORAGE=${AttemptSafeStorage}'
        ContainerEnvEntry23: !Sub 'PN_PAPERCHANNEL_ATTEMPTQUEUESAFESTORAGE=${AttemptQueueSafeStorage}'
        ContainerEnvEntry24: !Sub 'PN_PAPERCHANNEL_ATTEMPTQUEUENATIONALREGISTRIES=${AttemptQueueNationalRegistries}'
        ContainerEnvEntry25: !Sub 'PN_PAPERCHANNEL_ATTEMPTQUEUEEXTERNALCHANNEL=${AttemptQueueExternalChannel}'
        ContainerEnvEntry26: !Sub 'SPRING_CLOUD_FUNCTIONROUTER_QUEUES_LIST=${ExternalChannelsOutputsQueueName},${ExternalChannels2PaperChannelQueueName},${NationalRegistryGatewayOutputsQueueName},${ScheduledRequestsQueueName}'
        ContainerEnvEntry27: !Sub 'AWS_BUCKET_NAME=${PaperDeliveryDriversBucketName}'
        MappedPaths: '/paper-channel/*,/paper-channel-private/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref SubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn
        TaskRoleManagedPolicyArn: !Ref PaperChannelMicroserviceTaskPolicy

  PaperChannelMicroserviceTaskPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      #PolicyName: !Sub '${ProjectName}-paper-channel-CustomTaskPolicy'
      #Roles:
      #  - !GetAtt PaperChannelMicroservice.Outputs.TaskRoleName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub arn:aws:s3:::${PaperDeliveryDriversBucketName}
              - !Sub arn:aws:s3:::${PaperDeliveryDriversBucketName}/*
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:ChangeMessageVisibilityBatch
              - sqs:DeleteMessage
              - sqs:DeleteMessageBatch
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
              - sqs:SendMessageBatch
            Resource:
              - !Ref ExternalChannelsOutputsQueueARN
              - !Ref ExternalChannels2PaperChannelQueueARN
              - !Ref ScheduledRequestsQueueARN
              - !Ref NationalRegistryGatewayOutputsQueueARN
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
            Resource:
              - !Ref PCKmsEncDecDynamoDataKeyARN
          - Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ExecuteTransaction
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:TransactGetItems
              - dynamodb:TransactWriteItems
              - dynamodb:UpdateItem
            Resource:
              - !Sub "${RequestDeliveryDynamoTableArn}"
              - !Sub "${RequestDeliveryDynamoTableArn}/*"
              - !Sub "${DeliveryFileDynamoTableArn}"
              - !Sub "${DeliveryFileDynamoTableArn}/*"
              - !Sub "${AddressDynamoTableArn}"
              - !Sub "${AddressDynamoTableArn}/*"
              - !Sub "${TenderDynamoTableArn}"
              - !Sub "${TenderDynamoTableArn}/*"
              - !Sub "${DeliveryDriverDynamoTableArn}"
              - !Sub "${DeliveryDriverDynamoTableArn}/*"
              - !Sub "${CostDynamoTableArn}"
              - !Sub "${CostDynamoTableArn}/*"
              - !Sub "${ZoneDynamoTableArn}"
              - !Sub "${ZoneDynamoTableArn}/*"
              - !Sub "${CapDynamoTableArn}"
              - !Sub "${CapDynamoTableArn}/*"


  # Dashboard
  PaperChannelMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-paper-channel"
        AlarmArns: !Join
          - ','
          - - !GetAtt PaperChannelMicroservice.Outputs.FatalLogsMetricAlarmArn

#  PaperChannelGatewayDeliveryDriver:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
#      Parameters:
#        MicroServiceUniqueName: !Sub '${ProjectName}-PaperChannel-bo'
#        IntendedUsage: BACKOFFICE
#        DnsName: !Ref WebApiDnsName
#        ProjectName: !Ref ProjectName
#        ServiceApiPath: 'paper-channel/backoffice'
#        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
#        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
#        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
#        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn
#        OpenApiBucketName: !Ref MicroserviceBucketName
#        OpenApiBucketKey: !Sub ${MicroserviceBucketBaseKey}/docs/openapi/pn-paper-channel-v1.yaml
