AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
  PCKmsEncDecDynamoDataKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: A symmetric encryption KMS key AES-256-GCM
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  # Application use this alias to access the public key
  PCKmsEncDecDynamoDataKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub 'alias/${ProjectName}-paper-channel-dynamo'
      TargetKeyId: !Ref PCKmsEncDecDynamoDataKey

  RequestDeliveryDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}PaperRequestDelivery'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "fiscalCode"
          AttributeType: "S"
        - AttributeName: "correlationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "fiscal-code-index"
          KeySchema:
            - AttributeName: "fiscalCode"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "correlation-index"
          KeySchema:
            - AttributeName: "correlationId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  AddressDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}PaperAddress'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  TenderDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}PaperTender'
      AttributeDefinitions:
        - AttributeName: "idTender"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "idTender"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  DeliveryDriverDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}PaperDeliveryDriver'
      AttributeDefinitions:
        - AttributeName: "uniqueCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "uniqueCode"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  CostDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}PaperCost'
      AttributeDefinitions:
        - AttributeName: "idDeliveryDriver"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "N"
        - AttributeName: "cap"
          AttributeType: "S"
        - AttributeName: "zone"
          AttributeType: "S"
        - AttributeName: "idTender"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "idDeliveryDriver"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "SORT"
      GlobalSecondaryIndexes:
        - IndexName: "cap-index"
          KeySchema:
            - AttributeName: "cap"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "zone-index"
          KeySchema:
            - AttributeName: "zone"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "tender-index"
          KeySchema:
            - AttributeName: "idTender"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:

  PCKmsEncDecDynamoDataKeyARN:
    Description: Name of KMS Key for Dynamo encode/decode data
    Value: !Sub '${PCKmsEncDecDynamoDataKey.Arn}'

  RequestDeliveryDynamoTableName:
    Description: Name of dynamodb table containing request
    Value: !Ref RequestDeliveryDynamoTable

  RequestDeliveryDynamoTableArn:
    Description: ARN of dynamodb table containing request
    Value: !Sub '${RequestDeliveryDynamoTable.Arn}'

  AddressDynamoTableName:
    Description: Name of dynamodb table containing address of request delivery
    Value: !Ref AddressDynamoTable

  AddressDynamoTableArn:
    Description: ARN of dynamodb table containing address of request delivery
    Value: !Sub '${AddressDynamoTable.Arn}'

  TenderDynamoTableName:
    Description: Name of dynamodb table containing tenders
    Value: !Ref TenderDynamoTable

  TenderDynamoTableArn:
    Description: ARN of dynamodb table containing tenders
    Value: !Sub '${TenderDynamoTable.Arn}'

  DeliveryDriverDynamoTableName:
    Description: Name of dynamodb table containing delivery drivers
    Value: !Ref DeliveryDriverDynamoTable

  DeliveryDriverDynamoTableArn:
    Description: ARN of dynamodb table containing delivery drivers
    Value: !Sub '${DeliveryDriverDynamoTable.Arn}'

  CostDynamoTableName:
    Description: Name of dynamodb table containing cost
    Value: !Ref CostDynamoTable

  CostDynamoTableArn:
    Description: ARN of dynamodb table containing cost
    Value: !Sub '${CostDynamoTable.Arn}'
