AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
  PaperDeliveryDriversBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ObjectLockEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - "x-amz-version-id"

  PCKmsEncDecDynamoDataKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: A symmetric encryption KMS key AES-256-GCM
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  # Application use this alias to access the public key
  PCKmsEncDecDynamoDataKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub 'alias/${ProjectName}-paper-channel-dynamo'
      TargetKeyId: !Ref PCKmsEncDecDynamoDataKey

  # Internal queues
  ScheduledRequestsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-paper_channel_requests'
        DelaySeconds: 1

  RequestDeliveryDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PaperRequestDelivery'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "fiscalCode"
          AttributeType: "S"
        - AttributeName: "correlationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "fiscal-code-index"
          KeySchema:
            - AttributeName: "fiscalCode"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "correlation-index"
          KeySchema:
            - AttributeName: "correlationId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  AddressDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PaperAddress'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  TenderDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PaperTender'
      AttributeDefinitions:
        - AttributeName: "tenderCode"
          AttributeType: "S"
        - AttributeName: "author"
          AttributeType: "S"
        - AttributeName: "startDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "tenderCode"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "author-index"
          KeySchema:
            - AttributeName: "author"
              KeyType: "HASH"
            - AttributeName: "startDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  DeliveryDriverDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryDriver'
      AttributeDefinitions:
        - AttributeName: "uniqueCode"
          AttributeType: "S"
        - AttributeName: "tenderCode"
          AttributeType: "S"
        - AttributeName: "author"
          AttributeType: "S"
        - AttributeName: "startDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "uniqueCode"
          KeyType: "HASH"
        - AttributeName: "tenderCode"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "author-index"
          KeySchema:
            - AttributeName: "author"
              KeyType: "HASH"
            - AttributeName: "startDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  CostDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PaperCost'
      AttributeDefinitions:
        - AttributeName: "idDeliveryDriver"
          AttributeType: "S"
        - AttributeName: "uuid"
          AttributeType: "S"
        - AttributeName: "cap"
          AttributeType: "S"
        - AttributeName: "zone"
          AttributeType: "S"
        - AttributeName: "tenderCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "idDeliveryDriver"
          KeyType: "HASH"
        - AttributeName: "uuid"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "cap-index"
          KeySchema:
            - AttributeName: "cap"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "zone-index"
          KeySchema:
            - AttributeName: "zone"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "tender-index"
          KeySchema:
            - AttributeName: "tenderCode"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ZoneDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PaperZone'
      AttributeDefinitions:
        - AttributeName: "countryIt"
          AttributeType: "S"
        - AttributeName: "countryEn"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "countryIt"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "countryEn-index"
          KeySchema:
            - AttributeName: "countryEn"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  CapDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PaperCap'
      AttributeDefinitions:
        - AttributeName: "author"
          AttributeType: "S"
        - AttributeName: "cap"
            AttributeType: "S"
      KeySchema:
        - AttributeName: "author"
          KeyType: "HASH"
        - AttributeName: "cap"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  DeliveryFileDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryFile'
      AttributeDefinitions:
        - AttributeName: "uuid"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "uuid"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  PaperRequestErrorDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PaperRequestError'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "created"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
        - AttributeName: "created"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  PaperDeliveryDriversBucketName:
    Description: Name of s3 bucket
    Value: !Ref PaperDeliveryDriversBucket

  # Scheduled Requests
  ScheduledRequestsQueueName:
    Value: !GetAtt ScheduledRequestsQueue.Outputs.QueueName
    Description: pn-paper-channel input queue name
  ScheduledRequestsQueueURL:
    Value: !GetAtt ScheduledRequestsQueue.Outputs.QueueURL
    Description: pn-paper-channel input queue URL
  ScheduledRequestsQueueARN:
    Value: !GetAtt ScheduledRequestsQueue.Outputs.QueueARN
    Description: pn-paper-channel input queue ARN

  PCKmsEncDecDynamoDataKeyARN:
    Description: Name of KMS Key for Dynamo encode/decode data
    Value: !Sub '${PCKmsEncDecDynamoDataKey.Arn}'

  RequestDeliveryDynamoTableName:
    Description: Name of dynamodb table containing request
    Value: !Ref RequestDeliveryDynamoTable

  RequestDeliveryDynamoTableArn:
    Description: ARN of dynamodb table containing request
    Value: !Sub '${RequestDeliveryDynamoTable.Arn}'

  PaperRequestErrorTableName:
    Description: Name of dynamodb table containing request error
    Value: !Ref PaperRequestErrorDynamoTable

  PaperRequestErrorTableArn:
    Description: ARN of dynamodb table containing request error
    Value: !Sub '${PaperRequestErrorDynamoTable.Arn}'

  DeliveryFileDynamoTableName:
    Description: Name of dynamodb table containing file request
    Value: !Ref DeliveryFileDynamoTable

  DeliveryFileDynamoTableArn:
    Description: ARN of dynamodb table containing file request
    Value: !Sub '${DeliveryFileDynamoTable.Arn}'

  AddressDynamoTableName:
    Description: Name of dynamodb table containing address of request delivery
    Value: !Ref AddressDynamoTable

  AddressDynamoTableArn:
    Description: ARN of dynamodb table containing address of request delivery
    Value: !Sub '${AddressDynamoTable.Arn}'

  TenderDynamoTableName:
    Description: Name of dynamodb table containing tenders
    Value: !Ref TenderDynamoTable

  TenderDynamoTableArn:
    Description: ARN of dynamodb table containing tenders
    Value: !Sub '${TenderDynamoTable.Arn}'

  DeliveryDriverDynamoTableName:
    Description: Name of dynamodb table containing delivery drivers
    Value: !Ref DeliveryDriverDynamoTable

  DeliveryDriverDynamoTableArn:
    Description: ARN of dynamodb table containing delivery drivers
    Value: !Sub '${DeliveryDriverDynamoTable.Arn}'

  CostDynamoTableName:
    Description: Name of dynamodb table containing cost
    Value: !Ref CostDynamoTable

  CostDynamoTableArn:
    Description: ARN of dynamodb table containing cost
    Value: !Sub '${CostDynamoTable.Arn}'

  ZoneDynamoTableName:
    Description: Name of dynamodb table containing zone
    Value: !Ref ZoneDynamoTable

  ZoneDynamoTableArn:
    Description: ARN of dynamodb table containing zone
    Value: !Sub '${ZoneDynamoTable.Arn}'

  CapDynamoTableName:
    Description: Name of dynamodb table containing cap
    Value: !Ref CapDynamoTable

  CapDynamoTableArn:
    Description: ARN of dynamodb table containing cap
    Value: !Sub '${CapDynamoTable.Arn}'
