AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
  RequestDeliveryDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-request-delivery'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "fiscalCode"
          AttributeType: "S"
        - AttributeName: "correlationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "fiscal-code-index"
          KeySchema:
            - AttributeName: "fiscalCode"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "correlation-index"
          KeySchema:
            - AttributeName: "correlationId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  AddressDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-address'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
      TimeToLiveSpecification:
        - AttributeName: "ttl"
          Enabled: true
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
    KinesisStreamSpecification:
      StreamArn: !Ref CdcKinesisSourceStreamArn
    StreamSpecification:
      StreamViewType: NEW_IMAGE

Outputs:

  RequestDeliveryDynamoTableName:
    Description: Name of dynamodb table containing request
    Value: !Ref RequestDeliveryDynamoTable

  RequestDeliveryDynamoTableArn:
    Description: ARN of dynamodb table containing request
    Value: !Sub '${RequestDeliveryDynamoTable.Arn}'

  AddressDynamoTableName:
    Description: Name of dynamodb table containing address of request delivery
    Value: !Ref AddressDynamoTable

  AddressDynamoTableArn:
    Description: ARN of dynamodb table containing address of request delivery
    Value: !Sub '${AddressDynamoTable.Arn}'
