AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  DBName:
    Description: 'Database Name'
    Default: 'pnpaperchanneldb'
    Type: String

  DBPort:
    Description: 'TCP/IP Port for the Database Instance'
    Type: Number
    Default: 5432
    ConstraintDescription: 'Must be in the range [1150-65535]'
    MinValue: 1150
    MaxValue: 65535

  DBUsername:
    Description: 'Database master username'
    Default: 'pnpaperchanneluser'
    Type: String

  DBInstanceClass:
    Default: db.r6g.large
    Description: Database Instance Class
    Type: String

  DBSecretName:
    Description: 'Secret Name for database'
    Default: 'pn-paper-channel-db-secret'
    Type: String

Resources:
  AuroraMasterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref DBSecretName
      Description: !Join [ '', [ 'Aurora PostgreSQL Master User Secret ', !Ref 'AWS::StackName' ] ]
      GenerateSecretString:
        SecretStringTemplate: !Join [ '', [ '{"username": "', !Ref DBUsername, '"}' ] ]
        GenerateStringKey: "password"
        ExcludeCharacters: '"@/\'
        PasswordLength: 16

  RDSDBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Join [ "- ", [ "Aurora PG Cluster Parameter Group for  Pn-Paper-Channel ", !Ref DBName ] ]
      Family: 'aurora-postgresql14'
      Parameters:
        rds.force_ssl: 1

  RDSDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: 'DB PG Parameter Group'
      Family: 'aurora-postgresql14'

  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: '14.5'
      DatabaseName: !Ref DBName
      Port: !Ref DBPort
      MasterUsername: !Join [ '', [ '{{resolve:secretsmanager:', !Ref AuroraMasterSecret, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref AuroraMasterSecret, ':SecretString:password}}' ] ]
      DBClusterParameterGroupName: !Ref RDSDBClusterParameterGroup

  AuroraDBFirstInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      CopyTagsToSnapshot: true
      DBClusterIdentifier: !Ref AuroraDBCluster
      Engine: aurora-postgresql
      EngineVersion: '14.5'
      DBParameterGroupName: !Ref RDSDBParameterGroup
      PubliclyAccessible: false
      DBInstanceClass: !Ref DBInstanceClass

  AuroraDBSecondInstance:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - AuroraDBFirstInstance
    Properties:
      CopyTagsToSnapshot: true
      DBClusterIdentifier: !Ref AuroraDBCluster
      Engine: aurora-postgresql
      EngineVersion: '14.5'
      DBParameterGroupName: !Ref RDSDBParameterGroup
      PubliclyAccessible: false
      DBInstanceClass: !Ref DBInstanceClass

  RequestDeliveryDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-request-delivery'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "fiscalCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "fiscal-code-index"
          KeySchema:
            - AttributeName: "fiscalCode"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:

  DBName:
    Description: 'Database Name'
    Value: !Ref DBName

  DBClusterEndpoint:
    Description: 'Aurora Cluster/Writer Endpoint'
    Value: !GetAtt 'AuroraDBCluster.Endpoint.Address'

  DBReaderEndpoint:
    Description: 'Aurora Reader Endpoint'
    Value: !GetAtt 'AuroraDBCluster.ReadEndpoint.Address'

  DBPort:
    Description: 'Aurora Endpoint Port'
    Value: !GetAtt 'AuroraDBCluster.Endpoint.Port'

  DBSecretName:
    Description: 'Database Secret Name'
    Value: !Ref DBSecretName

  RequestDeliveryDynamoTableName:
    Description: Name of dynamodb table containing request
    Value: !Ref RequestDeliveryDynamoTable

  RequestDeliveryDynamoTableArn:
    Description: ARN of dynamodb table containing request
    Value: !Sub '${RequestDeliveryDynamoTable.Arn}'

  AuroraMasterSecretArn:
    Description: ARN of secret
    Value: !Sub '${AuroraMasterSecret.Arn}'