package it.pagopa.pn.paperchannel.middleware.queue.model;

public enum EventTypeEnum {

    SEND_ANALOG_RESPONSE,
    PREPARE_ANALOG_RESPONSE,
    NATIONAL_REGISTRIES_ERROR,
    EXTERNAL_CHANNEL_ERROR,
    F24_ERROR,
    SAFE_STORAGE_ERROR,
    MANUAL_RETRY_EXTERNAL_CHANNEL,
    ADDRESS_MANAGER_ERROR,
    PREPARE_ASYNC_FLOW,
    SEND_ZIP_HANDLE,
    ZIP_HANDLE_ERROR,
    REDRIVE_PAPER_PROGRESS_STATUS,
    PREPARE_PHASE_ONE_RESPONSE,
    OCR_REQUEST
}
